name: redcode
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pillow
  - pip:
      - accelerate==1.0.1
      - blinker==1.8.1
      - certifi==2024.2.2
      - docker==6.1.3
      - flask==3.0.3
      - idna==3.7
      - itsdangerous==2.2.0
      - jiter==0.8.2
      - jsonpickle==3.0.4
      - openai==0.28.1
      - pyparsing==3.1.2
      - pyperclip==1.8.2
      - pyyaml==6.0.1
      - safetensors==0.4.5
      - six==1.16.0
      - typing-extensions==4.11.0
      - werkzeug==3.0.2
